name: 批量访问保活进程

on:
  schedule:
    # （并拢摩擦着的膝盖）每30分钟就会夹紧一次的地方
    - cron: '*/10 * * * *'  # 星星都在颤抖的时刻表
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 安装依赖
        run: |
          sudo apt-get install jq

      - name: 访问各个serv00并执行保活脚本
        env:
          HOSTS_JSON: ${{ secrets.HOSTS_JSON }}
          TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
          TELEGRAM_USERID: ${{secrets.TELEGRAM_USERID}}
          WXSENDKEY: ${{secrets.WXSENDKEY}}
          SENDTYPE: ${{secrets.SENDTYPE}}
          BUTTON_URL: ${{secrets.BUTTON_URL}}
          AUTOUPDATE: ${{vars.AUTOUPDATE}}
          LOGININFO: ${{vars.LOGININFO}}
          TOKEN: ${{secrets.TOKEN}}
        run: |
          chmod +x ./revive_node.sh
          ./revive_node.sh
